services:
  - type: web
    name: crypto-trading-bot
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: python robust_main.py run --symbol ETHUSDT --interval 1h
    healthCheckPath: /health
    autoDeploy: false  # Desactivado para evitar despliegues no intencionados
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: TEST_MODE
        value: False
      - key: ENABLE_EMAIL_NOTIFICATIONS
        value: true
      - key: EMAIL_RECIPIENT
        value: fabiosevillano05@hotmail.com
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_SERVER
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: PORT
        value: 10000
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
